routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Route::get('/template', function() {
    return view('template.master');
});

Route::group(['prefix' => 'dashboard','middleware' => 'auth'], function(){
    Route::get('/', function() {
        return view('template.master');
    });
    // Permission
    Route::resource('/role/permissions', 'PermissionController');
    // Role
    Route::get('/role', 'Config\RoleController@index')->name('role.index');
    Route::get('/role/list', 'Config\RoleController@list')->name('role.list');

    
});

Auth::routes();


//role
Route::resource('/role', 'Config\RoleController')->middleware('auth');
Route::resource('/user', 'Config\UserController')->middleware('auth');
Route::get('/changepassword/{id}', 'Config\UserController@changePassword');
Route::put('/changepassword/store/{id}', 'Config\UserController@updatePassword');

// User
Route::get('user/download/template', 'Config\UserController@downloadTemplate');
Route::post('user/upload', 'Config\UserController@upload');
Route::get('user/upload/save', 'Config\UserController@saveUpload');
Route::get('user_ajax', 'Config\UserController@show_ajax')->name('user_ajax');

// Material Group
Route::resource('/materialgroup', 'Masters\MaterialGroupController');
Route::get('material_group_ajax', 'Masters\MaterialGroupController@show_ajax')->name('material_group_ajax');
// Route::get('/materialgroup', 'Masters\MaterialGroupController@index')->name('material_group.index');
// Route::post('/materialgroup/{id}', 'Masters\MaterialGroupController@update')->name('material_group.update');

//classification
Route::get('classification/materialused/{idClass}', 'Masters\ClassificationController@getmaterialused');
Route::post('classification/{id}/parameter', 'Masters\ClassificationController@paramclassific')->name('save.paramclassific');
Route::get('classification/editparam/{id_parameter}', 'Masters\ClassificationController@editparam');
Route::get('classification/{id_clasification}/addparameter', 'Masters\ClassificationController@addparam');
Route::put('editparam/{id_clasification}/{id_parameter}', 'Masters\ClassificationController@updateparam');
Route::delete('classification/paramclassificdestroy/{id_parameter}', 'Masters\ClassificationController@paramclassificdestroy');
Route::resource('classification', 'Masters\ClassificationController');
Route::get('classification_ajax', 'Masters\ClassificationController@show_ajax')->name('classification_ajax');

//material
Route::resource('material', 'Masters\MaterialController');
Route::get('material/assetused/{id}', 'Masters\MaterialController@getassetused');
Route::get('material/assetusedpdf/{id}', 'Masters\MaterialController@getAssetAsedPdf');
Route::delete('material/image/{id}', 'Masters\MaterialController@delete_image');
Route::get('material/classification/{id}.ajax', 'Masters\MaterialController@ajax_parameter')->name('material.classification.ajax');
Route::post('material/{id}/parameter', 'Masters\MaterialController@parameter');
Route::post('material/{id}/image', 'Masters\MaterialController@upload_images')->name('material.images.upload');
Route::get('material/{id}/image', 'Masters\MaterialController@get_images')->name('material.images.list');
Route::get('material/download/template', 'Masters\MaterialController@downloadTemplate');
Route::post('material/upload', 'Masters\MaterialController@upload');
Route::get('material/upload', 'Masters\MaterialController@index');
Route::get('material/upload/save', 'Masters\MaterialController@saveData');
Route::get('material-active', 'Masters\MaterialController@show_active_ajax')->name('material_active');
Route::get('material_ajax', 'Masters\MaterialController@show_ajax')->name('material_ajax');

//master supplier
Route::resource('supplier', 'Masters\SupplierController');
Route::get('autocomplete_supplier_building', 'Masters\SupplierController@autocompletebuilding')->name('autocomplete.supplier.building.ajax');
Route::get('autocomplete_supplier_unit', 'Masters\SupplierController@autocompleteunit')->name('autocomplete.supplier.unit.ajax');
Route::get('supplier_ajax', 'Masters\SupplierController@show_ajax')->name('supplier_ajax');

//setting (Asset Status - Type - Material Group - Retired Reason - ValuationGroup)
Route::resource('assettype', 'Masters\AssetTypeController');
Route::resource('valuationgroup', 'Masters\ValuationGroupController');
Route::resource('statusasset', 'Masters\AssetStatusController');
Route::resource('retiredreason', 'Masters\RetiredReasonController');
Route::get('status_ajax', 'Masters\AssetStatusController@ajaxStatus')->name('status_ajax');
Route::get('retired_reason_ajax', 'Masters\RetiredReasonController@ajaxretiredreason')->name('retired_reason_ajax');
Route::get('assettype-ajax', 'Masters\AssetTypeController@show_ajax')->name('assettype_ajax');
Route::get('groupowner-ajax', 'Config\RoleController@show_ajax')->name('groupowner_ajax');
Route::get('valuationgroup-ajax', 'Masters\ValuationGroupController@show_ajax')->name('valuationgroup_ajax');

//Plant
Route::resource('system/plant', 'Masters\PlantController');

Route::get('plant-active-ajax', 'Masters\PlantController@show_active_ajax')->name('plant_active_ajax');


//asset
//Route::get('update_responsible', 'Transaction\AssetController@update_responsible')->name('update_responsible');
Route::post('asset/{id_asset}/location', 'Transaction\AssetController@storehistoryloc');
Route::post('asset/{id_asset}/person', 'Transaction\AssetController@storehistoryperson');
Route::resource('asset', 'Transaction\AssetController');
Route::get('asset/{id_asset}/classification', 'Transaction\AssetController@classification');
Route::post('asset/{code_asset}/value', 'Transaction\AssetController@storevalue')->name('save.value');
Route::post('asset/upload', 'Transaction\AssetController@upload');
// Route::post('asset/upload/store', 'Transaction\AssetController@uploadStore');
// Route::get('asset/upload/success', 'Transaction\AssetController@uploadStoreSuccess');
Route::get('asset/upload/save', 'Transaction\AssetController@saveData');
Route::get('asset/download/template', 'Transaction\AssetController@downloadTemplate');
Route::post('asset/{id}/value', 'Transaction\AssetController@storevalue');
Route::post('asset/{id}/image', 'Transaction\AssetController@upload_images')->name('asset.images.upload');
Route::get('asset/{id}/image', 'Transaction\AssetController@get_images')->name('asset.images.list');
Route::delete('asset/image/{id}', 'Transaction\AssetController@delete_image');
Route::post('asset/{id}/image360', 'Transaction\AssetController@upload_images360')->name('asset.images360.upload');
Route::get('asset/{id}/image360', 'Transaction\AssetController@get_images360')->name('asset.images360.list');
Route::delete('asset/image360/{id}', 'Transaction\AssetController@delete_image360');
Route::get('asset/material/{id}.ajax', 'Transaction\AssetController@ajax_description')->name('asset.material.ajax');
Route::get('autocomplete', 'Transaction\AssetController@autocomplete')->name('autocomplete.ajax');
Route::get('superior_asset_ajax', 'Transaction\AssetController@ajaxSuperiorAsset')->name('superior_asset_ajax');
Route::get('export/asset', 'Transaction\AssetController@export');
Route::get('savefilter/asset', 'Transaction\AssetController@savefilter');
Route::get('barcode/asset', 'Transaction\AssetController@tes_pdf');
Route::get('print_barcode/asset/{id}', 'Transaction\AssetController@one_pdf');
Route::post('asset/{id_asset}/area', 'Transaction\AssetController@area');
Route::get('asset_ajax', 'Transaction\AssetController@show_ajax')->name('asset_ajax');
Route::get('asset-stock', 'Transaction\AssetController@assetStock')->name('asset-stock');

// asset-refund
Route::get('asset-refund', 'Transaction\AssetController@refund');
Route::post('refund-ajax', 'Transaction\AssetController@refundAjax')->name('refund_ajax');
Route::post('refund-ajax-not', 'Transaction\AssetController@refundAjaxNot')->name('refund_ajax_not');
Route::get('export-refund/{id}', 'Transaction\AssetController@exportRefund')->name('export_refund');
Route::post('asset-refund-ajax', 'Transaction\AssetController@assetRefundAjax')->name('asset-refund-ajax');


// asset-handover
Route::resource('asset-handover', 'Transaction\AssetHandoverController');
//Route::get('asset-handover-create', 'Transaction\AssetController@assetHandovercreate');
Route::post('asset-handover-store-header', 'Transaction\AssetHandoverController@storeHeader')->name('asset-handover-store-header');
Route::post('asset-handover-store-line', 'Transaction\AssetHandoverController@storeLine')->name('asset-handover-store-line');
Route::delete('asset-handover-remove-line/{id}', 'Transaction\AssetHandoverController@destroyLine')->name('asset-handover-remove-line');
Route::post('asset-handover-update-header', 'Transaction\AssetHandoverController@updateHeader')->name('asset-handover-update-header');
Route::get('asset-handover-printed', 'Transaction\AssetHandoverController@assetHandover')->name('asset-handover-printed');
Route::get('asset-handover-pdf/{id}', 'Transaction\AssetHandoverController@pdfHandover')->name('asset-handover-pdf');
Route::get('asset-handover-document', 'Transaction\AssetHandoverController@documentList')->name('asset-handover-document');
Route::get('test2', 'Transaction\AssetHandoverController@test2');
/*
Route::post('refund-ajax', 'Transaction\AssetController@refundAjax')->name('refund_ajax');
Route::post('refund-ajax-not', 'Transaction\AssetController@refundAjaxNot')->name('refund_ajax_not');
Route::get('export-refund/{id}', 'Transaction\AssetController@exportRefund')->name('export_refund');

resources/views/region/create.blade.php
@extends('template.master')
@section('header')
Plant Master
@endsection
@section('content')
<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading panel-heading-divider icon-container">
                <a href="{{ url('system/region') }}" class="icon" title="Back"><span class="mdi mdi-arrow-left"></span></a><span class="icon-class"></span>
                Create New Plant<span class="panel-subtitle"></span>
            </div>
            <div class="panel-body">
                @if(session()->has('message.level'))
                    <div class="alert alert-{{ session('message.level') }}">
                        {!! session('message.content') !!}
                    </div>
                @endif
                <form class="form-horizontal group-border-dashed" role="form" method="POST" action="{{ url('system/region') }}">
                    {{ csrf_field() }}
                    <div class="row">   
                        <div class="col-md-12">
                            <div class="form-group {{ $errors->has('region_bismo') ? ' has-error' : '' }}">
                                <div class="col-sm-4">
                                <label class="control-label">Plant<font size="3" color="red"> *</font></label>
                                <input type="text" class="form-control field-reg-bismo field-name" name="region_bismo" id="region_bismo" autofocus value="{{ old('region_bismo') }}" maxlength="30" required>
                                    @if ($errors->has('region_bismo'))
                                        <p class="text-bold text-danger">{{ $errors->first('region_bismo') }}</p>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                    <div class="col-sm-12">
                                    <label class="control-label">Address<font size="3" color="red"> *</font></label>
                                    <input type="text" class="form-control clearme" id="us2-address" name="wil_reg" id="wil_reg" placeholder="Address" value="{{ old('wil_reg') }}">
                                        <input type="hidden" class="form-control" style="width: 110px" id="us2-lon" name="longitude" />
                                        <input type="hidden" class="form-control" style="width: 110px" id="us2-lat" name="latitude" />
                                        <br>
                                        <div id="us2" style="width: 100%; height: 300px;"></div>
                                    </div> 
                            </div>
                            <div class="form-group {{ $errors->has('keterangan') ? ' has-error' : '' }}">
                                <div class="col-sm-12">
                                <label class="control-label">Description</label>
                                <textarea rows="4" class="form-control field-ket input-sm field-name" name="keterangan" id="keterangan" maxlength="100">{{ old('keterangan') }}</textarea>
                                    @if ($errors->has('keterangan'))
                                        <p class="text-bold text-danger">{{ $errors->first('keterangan') }}</p>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row xs-pt-15">
                        <div class="col-xs-12">
                            <p class="text-right">
                                <button type="submit" class="btn btn-primary btn-lg">Save</button>
                                {{--  <a href="{{ url('system/region') }}" class="btn btn-default">Back</a>  --}}
                            </p>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
    


@endsection
@section('afterscript')
<!-- <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key={{ env('GOOGLE_MAPS_KEY') }} &libraries=places"></script>  -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBat0J0W6eArCkCSjkEX3FN9Tt8gSKmcRc&libraries=places"></script>
<script type="text/javascript">
$(document).ready(function(){  
    $('.clearme').focus(function() { 
                $(this).val(''); 
            });
    $(function() {
        $('#us2').locationpicker({
            location: {
                latitude: "-6.189680",
                longitude: "106.823440"
            },
            inputBinding: {
                latitudeInput: $('#us2-lat'),
                longitudeInput: $('#us2-lon'),
                locationNameInput: $('#us2-address'),                
            },
            radius:0,
            enableAutocomplete: true       
        });
    }); 
});
</script> 
@endsection

resources/views/region/edit.blade.php
@extends('template.master')
@section('header')
Plant Master
@endsection
@section('content')


<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading panel-heading-divider icon-container">
                <a href="{{ url('system/plant') }}" class="icon" title="Back"><span class="mdi mdi-arrow-left"></span></a><span class="icon-class"></span>
                Edit Plant<span class="panel-subtitle"></span>
            </div>
            <div class="panel-body">
                @if(session()->has('message.level'))
                    <div class="alert alert-{{ session('message.level') }}">
                        {!! session('message.content') !!}
                    </div>
                @endif
                <form class="form-horizontal group-border-dashed" role="form" method="POST" action="{{ route('plant.update', ['id' => $plants->id]) }}">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="put" />
                    <input type="hidden" name="usr_created" id="usr_created" value="{{ $plants->create_by }}" />
                    <div class="row">   
                        <div class="col-md-12">
                            <div class="form-group {{ $errors->has('plant_name') ? ' has-error' : '' }}">
                                <div class="col-sm-4">
                                <label class="control-label">Plant<font size="3" color="red"> *</font></label>
                                <input type="text" class="form-control field-reg-bismo field-name" name="plant_name" id="plant_name" autofocus value="{{ $plants->name }}" maxlength="30" required>
                                    @if ($errors->has('plant_name'))
                                        <p class="text-bold text-danger">{{ $errors->first('plant_name') }}</p>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                    <div class="col-sm-12">
                                    <label class="control-label">Address<font size="3" color="red"> *</font></label>
                                    <input type="text" class="form-control clearme" id="us2-address" name="wil_reg" id="wil_reg" placeholder="Address" value="{{ old('wil_reg') }}">
                                        <input type="hidden" class="form-control" style="width: 110px" id="us2-lon" name="longitude" />
                                        <input type="hidden" class="form-control" style="width: 110px" id="us2-lat" name="latitude" />
                                        <br>
                                        <div id="us2" style="width: 100%; height: 300px;"></div>
                                    </div> 
                            </div>
                            <div class="form-group {{ $errors->has('description') ? ' has-error' : '' }}">
                                <div class="col-sm-12">
                                <label class="control-label">Description</label>
                                <textarea rows="4" class="form-control field-ket input-sm field-name" name="description" id="description" maxlength="100" value="{{ $plants->description }}">{{ $plants->description }}</textarea>
                                    @if ($errors->has('description'))
                                        <p class="text-bold text-danger">{{ $errors->first('description') }}</p>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row xs-pt-15">
                        <div class="col-xs-12">
                            <p class="text-right">
                                <button type="submit" class="btn btn-primary btn-lg">Save</button>
                                {{--  <a href="{{ url('system/plant') }}" class="btn btn-default">Back</a>  --}}
                            </p>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



@endsection
@section('afterscript')
   <!-- <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key={{ env('GOOGLE_MAPS_KEY') }} &libraries=places"></script>  -->
   <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBat0J0W6eArCkCSjkEX3FN9Tt8gSKmcRc&libraries=places"></script>
   <script type="text/javascript">
       $(document).ready(function(){
           $('.clearme').focus(function() { 
               $(this).val(''); 
           });
       });
       $(function() {
           $('#us2').locationpicker({
               location: {
                   latitude: "{{ $plants->latitude }}",
                   longitude: "{{ $plants->longitude }}"
               },
               inputBinding: {
                   latitudeInput: $('#us2-lat'),
                   longitudeInput: $('#us2-lon'),
                   locationNameInput: $('#us2-address')
               },
               radius:0,
               enableAutocomplete: true       
           });
       }); 
   </script> 
@endsection

resources/views/region/index.blade.php
@extends('template.master')
@section('header')
Plant Master
@endsection
@section('content')
<div class="row">
    <div class="col-md-12">

        @if(Session::has('message'))
            <div class="alert alert-success alert-dismissible">
                <a class="close" data-dismiss="alert">×</a>
                {!!Session::get('message')!!}
            </div>
        @endif
        
        <div class="panel panel-default panel-table">

            <div class="panel-heading icon-container">
                <a href="{{ url('system/region/create') }}" class="icon" title="Add Data"><span class="mdi mdi-plus"></span></a><span class="icon-class"></span>
                Plant List
            </div>

            <div class="panel-body">
                <div class="pull-left" style="margin-left: 10px;">
                    <form>
                        <div>
                        <select id="limit-row" name="limit" class="form-control">
                            <option {{ request()->has('limit') && request()->limit==10?'selected':'' }} value="10">10</option>
                            <option {{ request()->has('limit') && request()->limit==25?'selected':'' }} value="25">25</option>
                            <option {{ request()->has('limit') && request()->limit==100?'selected':'' }} value="100">100</option>
                        </select>
                        </div>
                    </form>
                </div>
                <div class="pull-right" style="margin-right: 10px;">
                    <input id="search-input" class="form-control" placeholder="Search" type="text" name="q" value="@if(request()->has('q')){{ request()->q}}@endif" />
                </div>
                <table id="table12" class="table table-striped table-hover table-fw-widget" width="100%">
                    <thead>
                        <tr>
                            <th style="width: 5%">No</th>
                            <th>Plant</th>
                            <!-- <th>Region FMS</th> -->
                            <th>Description</th>
                            <th style="width: 11%;">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php $i = 1 @endphp
                        @foreach($regions as $reg)
                            <tr>
                                <td>{{ $i }}</td>
                                <td>{{ $reg->region_bismo }}</td>
                                {{--  <!-- <td>{{ $reg->region_fms }}</td> -->  --}}
                                <td>{{ $reg->keterangan }}</td>
                                <td class="actions">
                                <form id="form-delete{{$i}}" method="post" action="{{ url('system/region/'. $reg->region_bismo) }}" class="pull-right">
                                        {!! csrf_field() !!}
                                        <input type="hidden" name="_method" value="DELETE" />
                                    </form>
        
                                    <div class="btn-group btn-space">
                                        <a href="{{ url('system/region/'. $reg->region_bismo) }}" type="button" class="btn btn-default">Detail</a>
                                        <button type="button" data-toggle="dropdown" class="btn btn-primary dropdown-toggle"><span class="mdi mdi-chevron-down"></span><span class="sr-only">Toggle Dropdown</span></button>
                                        <ul role="menu" class="dropdown-menu" style="min-width:100px" >
                                            <li><a href="{{ url('system/region/'. $reg->region_bismo .'/edit') }}" ><i class="mdi mdi-edit"> </i> Edit</a></li>
                                            <li><a href="#" onclick="delete_data({{$i}})" type="submit"><i class="text-danger mdi mdi-delete"> </i> Delete</a></li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        @php $i++ @endphp
                        @endforeach
                    </tbody>
                </table>
                <div class="text-center">
                    <?php
                    $appends = [];
                    if(request()->has('q')) $appends['q'] = request()->q;
                    if(request()->has('limit')) $appends['limit'] = request()->limit;
                    ?>
                    {{ $regions->appends($appends)->links() }}
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('afterscript')
<script>
    function delete_data(val){
        if (confirm('Are you sure delete this data?')){
            $('#form-delete'+val).submit();
        }
    }

    $(function() {
        $('#table12').DataTable({
            // "paging": true,
            // "lengthChange": true,
            // "searching": true,
            // "ordering": false,
            // "info": true,
            // "autoWidth": true,
            // // "scrollX": true,
            "paging": false,
            "lengthChange": false,
            "searching": false,
            "ordering": false,
            "info": true,
            "autoWidth": true,
            "scrollX": true,
            // "responsive": true,
            "scrollY": "400px",
        });         
    });

    $('#limit-row').change(function(){
        window.location.replace("{{ url('system/region') }}?q="+$("#search-input").val()+"&limit="+$("#limit-row").val());
    });

    $('#search-input').keypress(function (e) {
        if(e.which == 13) {
            window.location.replace("{{ url('system/region') }}?q="+$("#search-input").val()+"&limit="+$("#limit-row").val());
        }
    });
</script>
@endsection

resources/views/region/show.blade.php
@extends('template.master')
@section('header')
Plant Master
@endsection
@section('content')

<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-default">
			<div class="panel-heading panel-heading-divider icon-container">
				<a href="{{ url('system/region') }}" class="icon" title="Back"><span class="mdi mdi-arrow-left"></span></a><span class="icon-class"></span>
				Detail Plant<span class="panel-subtitle"></span>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-12">
						<table class="table table-striped table-hover table-fw-widget">
							<tr>
								<th>Plant</th>
								<td>{{ $regions->region_bismo }}</td>
							</tr>
							<tr>
								<th width="150">Keterangan</th>
								<td>{{ $regions->keterangan }}</td>
							</tr>
							<tr>
								<th>Address</th>
								<td id="td-address">
									<textarea class="form-control" id="us2-address" rows="2" disabled="">
										
									</textarea>
								</td>
                                <input type="hidden" class="form-control" style="width: 110px" id="us2-lon" name="longitude" />
                                <input type="hidden" class="form-control" style="width: 110px" id="us2-lat" name="latitude" />
							</tr>
						</table>						
					</div>
				</div>
				<div class="row xs-pt-15">
					<div class="col-xs-12">
						<btn href="#bar" data-toggle="collapse" class="btn btn-success" onclick="ShowHide(this);">Show Map</btn>
					</div>
				</div>
					
				<div class="row xs-pt-15">
					<div class="col-xs-12">
						<div id="bar" class="collapse">
							<td><div id="show-map" style="width: 100%; height: 300px;"></div></td>
						</div>
					</div>	
				</div>
			</div>
			
		</div>
	</div>
</div>

@endsection

@section('afterscript')
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBat0J0W6eArCkCSjkEX3FN9Tt8gSKmcRc&libraries=places"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('.clearme').focus(function() { 
            $(this).val(''); 
        });
    });
    $(function() {
        $('#show-map').locationpicker({
            location: {
                latitude: "{{ $regions->latitude }}",
                longitude: "{{ $regions->longitude }}"
            },
            inputBinding: {
               latitudeInput: $('#us2-lat'),
               longitudeInput: $('#us2-lon'),
               locationNameInput: $('#us2-address')
           	},
            radius:0,
            draggable: false
            // zoom: 20
        });
    }); 
</script>

<script type="text/javascript">
// $(window).load(function () {
//    $('#bar').removeClass('in')
   

// });

function ShowHide(id) {
  if ($(id).html() == "Show Map") {
    $(id).html("Hide Map");
  } else {
    $(id).html ("Show Map");
  }

}
</script> 
@endsection